addpath Part1
addpath Part2
addpath Part3
addpath Part4
addpath data
%%
set(groot,  'DefaultLineLineWidth', 2, ....
            'DefaultAxesLineWidth', 1.5, ...
            'DefaultStemLineWidth', 2, ...
            'DefaultStemMarker', 'none', ...
            'DefaultAxesFontSize', 20, ...
            'DefaultAxesBox', 'on', ...
            'DefaultAxesColor', [1, 1, 1], ...
            'DefaultFigureColor', [1, 1, 1], ...
            'DefaultFigureInvertHardcopy', 'off', ...
            'DefaultFigurePaperUnits', 'inches', ...
            'DefaultFigureUnits', 'inches', ...
            'DefaultFigurePaperPosition', [0, 0, 5, 5], ...
            'DefaultFigurePaperSize', [8, 8], ...
            'DefaultFigurePosition', [0.1, 0.1, 7, 5], ...
            'DefaultLineMarkerSize', 20);
        
COLORS = get(groot, 'factoryAxesColorOrder');
% set default seed
rng(0);